version: '3.1'
services:
  db:
    image: mariadb
    container_name: "mysql"
    hostname: db
    restart: always
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci'
    ]
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "shizeying"
      MYSQL_ROOT_PASSWORD: "shizeying"
      TZ: "Asia/Shanghai"
    ports:
      - "33060:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./log:/var/log/mysql