version: '3'
services:
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:1.11.0
    container_name: odfe-node1
    environment:
      - cluster.name=single-node
      - node.name=single-node
      - network.host=0.0.0.0
      - discovery.type=single-node
      - bootstrap.memory_lock=false
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    ports:
      - 9201:9200
      - 9600:9600
      - 9301:9300
      - 9650:9650


  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.11.0
    container_name: odfe-kibana
    ports:
      - 5602:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://odfe-node1:9200
      ELASTICSEARCH_HOSTS: https://odfe-node1:9200
      i18n.locale: "zh-CN"
      server.host: "0.0.0.0"
    depends_on:
      - odfe-node1



