version: '3.7'
services:
  es01:
    env_file:
      - .env
    image: ${elasticsearch}:${version}
    container_name: es01
    hostname: es01
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch/es01.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./config/elasticsearch/java.policy:/usr/share/elasticsearch/jdk/conf/security/java.policy
      - ./config/elasticsearch/synonym.dic:/usr/share/elasticsearch/config/synonym/synonym.dic
      #- ./config/elasticsearch/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
      - ./config/elasticsearch/elastic-stack-ca.p12:/usr/share/elasticsearch/config/elastic-stack-ca.p12
      - ./config/elasticsearch/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./data/es01:/usr/share/elasticsearch/data
      - ./logs/es01:/usr/share/elasticsearch/logs
    
    ports:
      - 5001:5000
      - 9201:9200
      - 9301:9300
    networks:
      - elastic
  es02:
    env_file:
      - .env
    image: ${elasticsearch}:${version}
    container_name: es02
    hostname: es02
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9202:9200
      - 9302:9300
      - 5002:5000
    volumes:
      - ./config/elasticsearch/es02.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./config/elasticsearch/java.policy:/usr/share/elasticsearch/jdk/conf/security/java.policy
      - ./config/elasticsearch/synonym.dic:/usr/share/elasticsearch/config/synonym/synonym.dic
      - ./config/elasticsearch/elastic-stack-ca.p12:/usr/share/elasticsearch/config/elastic-stack-ca.p12
      - ./config/elasticsearch/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./data/es02:/usr/share/elasticsearch/data
      - ./logs/es02:/usr/share/elasticsearch/logs
    
    networks:
      - elastic
  es03:
    env_file:
      - .env
    image: ${elasticsearch}:${version}
    container_name: es03
    hostname: es03
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    ports:
      - 9203:9200
      - 9303:9300
      - 5003:5000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch/es03.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./config/elasticsearch/java.policy:/usr/share/elasticsearch/jdk/conf/security/java.policy
      - ./config/elasticsearch/synonym.dic:/usr/share/elasticsearch/config/synonym/synonym.dic
      - ./config/elasticsearch/elastic-stack-ca.p12:/usr/share/elasticsearch/config/elastic-stack-ca.p12
      - ./config/elasticsearch/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./data/es03:/usr/share/elasticsearch/data
      - ./logs/es03:/usr/share/elasticsearch/logs
    networks:
      - elastic
  es04:
    env_file:
      - .env
    image: ${elasticsearch}:${version}
    container_name: es04
    hostname: es04
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch/es04.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./config/elasticsearch/java.policy:/usr/share/elasticsearch/jdk/conf/security/java.policy
      - ./config/elasticsearch/synonym.dic:/usr/share/elasticsearch/config/synonym/synonym.dic
      - ./config/elasticsearch/elastic-stack-ca.p12:/usr/share/elasticsearch/config/elastic-stack-ca.p12
      - ./config/elasticsearch/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./data/es04:/usr/share/elasticsearch/data
      - ./logs/es04:/usr/share/elasticsearch/logs
    
    ports:
      - 5004:5000
      - 9204:9200
      - 9304:9300
    networks:
      - elastic
  es05:
    env_file:
      - .env
    image: ${elasticsearch}:${version}
    container_name: es05
    hostname: es05
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9205:9200
      - 9305:9300
      - 5005:5000
    networks:
      - elastic
    volumes:
      - ./config/elasticsearch/es05.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./config/elasticsearch/java.policy:/usr/share/elasticsearch/jdk/conf/security/java.policy
      - ./config/elasticsearch/synonym.dic:/usr/share/elasticsearch/config/synonym/synonym.dic
      - ./config/elasticsearch/elastic-stack-ca.p12:/usr/share/elasticsearch/config/elastic-stack-ca.p12
      - ./config/elasticsearch/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./data/es05:/usr/share/elasticsearch/data
      - ./logs/es05:/usr/share/elasticsearch/logs

  appsearch:
    container_name: appsearch
    hostname: appsearch
    image: ${appsearch}:${version}
    restart: always
    privileged: true
    ports:
      - 3002:3002
    volumes:
      - ./config/appsearch/config:/usr/share/enterprise-search/config
      - ./config/appsearch/filebeat:/usr/share/enterprise-search/filebeat
      - ./data/kibana:/usr/share/kibana/data
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    depends_on:
      - es01
      - es02
      - es03
      - es04
      - es05
  
  #  filebeat:
  #    # 容器名称
  #    container_name: filebeat
  #    # 主机名称
  #    hostname: filebeat
  #    # 镜像
  #    image: docker.elastic.co/beats/filebeat:7.4.2
  #    # 重启机制
  #    privileged: true
  #    environment:
  #      - TZ=Asia/Shanghai
  #      - LANG=C.UTF-8
  #    # 持久化挂载
  #    volumes:
  #      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #      # 映射到容器中 [作为数据源]
  #      - ./logs/filebeat/:/usr/share/filebeat/logs
  #      - ./data/filebeat:/usr/share/filebeat/data
  #    # 将指定容器连接到当前连接，可以设置别名，避免 ip 方式导致的容器重启动态改变的无法连接情况
  #    links:
  #      - es01
  #      - es02
  #      - es03
  #      - es04
  #      - es05
  #      #      - logstash
  #      - kibana
  #    # 依赖服务 [可无]
  #    depends_on:
  #      - es01
  #      - es02
  #      - es03
  #      - es04
  #      - es05
  #      - logstash
  #      - kibana
  #  logstash:
  #    container_name: logstash
  #    hostname: logstash
  #    image: logstash:7.13.0
  #    command: logstash -f ./conf/logstash-filebeat.conf
  ##    restart: always
  #    privileged: true
  #    volumes:
  #      # 映射到容器中
  #      - ./config/logstash/logstash-filebeat.conf:/usr/share/logstash/conf/logstash-filebeat.conf
  #    environment:
  ##      - elasticsearch.hosts=http://elasticsearch:9200
  #      # 解决 logstash 监控连接报错
  ##      - xpack.monitoring.elasticsearch.hosts=http://elasticsearch:9200
  #      - TZ=Asia/Shanghai
  #      - LANG=C.UTF-8
  #    ports:
  #      - 5044:5044/tcp
  #      - 9600:9600/tcp
  #    links:
  #      - es01
  #      - es02
  #      - es03
  #      - es04
  #      - es05
  #      - kibana
  #    depends_on:
  #      - es01
  #      - es02
  #      - es03
  #      - es04
  #      - es05
  #      - kibana

  kibana:
    env_file:
      - .env
    container_name: kibana
    hostname: kibana
    image: ${kibana}:${version}
    restart: always
    privileged: true
    ports:
      - 5601:5601
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./config/kibana/kibana:/usr/share/kibana/bin/kibana
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    networks:
      - elastic
    links:
      - es01
      - es02
      - es03
      - es04
      - es05
    depends_on:
      - es01
      - es02
      - es03
      - es04
      - es05
volumes:
  data04:
    driver: local
  data05:
    driver: local
  data06:
    driver: local

networks:
  elastic:
    driver: bridge