FROM wurstmeister/kafka:2.12-2.5.0
ENV LANG=C.UTF-8
ENV TIME_ZONE=Asia/Shanghai
RUN apk update && apk add --no-cache tzdata && \
        ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  && \
        /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 "$LANG" || true && \
            echo "export LANG=$LANG" > /etc/profile.d/locale.sh
ENV TZ="Asia/Shanghai"
WORKDIR /opt/kafka
