version: '3'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
  
  sonar:
    image: sonarqube
    container_name: sonar
    depends_on:
      - postgres
    volumes:
      - ./sonar/sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonar/sonarqube/logs:/opt/sonarqube/logs
      - ./sonar/sonarqube/data:/opt/sonarqube/data
      - ./sonar/sonarqube/conf:/opt/sonarqube/conf
    ports:
      - 9000:9000
    command:
      # 内存设置
      - -Dsonar.ce.javaOpts=-Xmx2048m
      - -Dsonar.web.javaOpts=-Xmx2048m
      # nginx 反向代理
      - -Dsonar.web.context=/sonar
      # crowd 集成，实现统一登录
      #- -Dsonar.security.realm=Crowd
      #- -Dcrowd.url=http://x.x.x.x:8095/crowd
      #- -Dcrowd.application=sonar
      #- -Dcrowd.password=xxxxxx
      #- -Dsonar.security.localUsers=admin
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar