version: '3.1'


services:
  #ngnix
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    privileged: true
    ports:
      - 80:80
    volumes:
      - /work/nginx/html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
    environment:
      TZ: Asia/Shanghai
      LANG: C.UTF-8