version: '3'

services:

  mysql-db-dev:
    container_name: kg-mysql        # 指定容器的名称
    image: mysql:8.0                   # 指定镜像和版本
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    #env_file: 设置环境变量文件
    #  - .env
    volumes:
#      - ./data:/var/lib/mysql"           # 挂载数据目录
#      - ./conf.d:/etc/mysql/conf.d"      # 挂载配置文件目录
      - ./my.cnf:/etc/my.cnf
