version: '3.7'

services:

  #mongodb
  mongodb:
    image: mongo
    restart: always
#    privileged: true
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
#      - ./data/mongodb:/data/db
      - ./config/mongod.conf.orig:/etc/mongod.conf.orig
    environment:
      TZ: Asia/Shanghai
      LANG: C.UTF-8










