version: '3'
services:
  #kafka
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    privileged: true
    hostname: zookeeper
#    volumes:
#      - ./data/zookeeper:/data
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    privileged: true
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: mac.local
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://mac.local:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
    volumes:
      - ./logs/kafka/kafka-logs:/kafka
    depends_on:
      - zookeeper
